<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.0000" tests="3" failures="1">
  <testsuite name="Root Suite" timestamp="2020-12-24T16:53:40" tests="0" file="cypress\integration\branch.js" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Branch" timestamp="2020-12-24T16:53:40" tests="3" time="0.0000" failures="1">
    <testcase name="Branch &quot;before each&quot; hook for &quot;Create Branch&quot;" time="0.0000" classname="&quot;before each&quot; hook for &quot;Create Branch&quot;">
      <failure message="The following error originated from your application code, not from Cypress.

  &gt; Cannot set property &apos;inject&apos; of undefined

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Branch`" type="TypeError"><![CDATA[TypeError: The following error originated from your application code, not from Cypress.

  > Cannot set property 'inject' of undefined

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Branch`
    at https://app.kudabank.com/login/:1:3977]]></failure>
    </testcase>
  </testsuite>
</testsuites>